language: node_js
services:
  - docker
node_js:
  - "stable"

before_install:
  - docker build .
  - docker ps -a
  - docker run "cd /root/service; npm test"

cache:
  directories:
    - "node_modules"