language: node_js
services:
  - docker
node_js:
  - "stable"

before_install:
  - docker build -t carlad/sinatra .
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/test-ci; npm test"

cache:
  directories:
    - "node_modules"