language: node_js
services:
  - docker
node_js:
  - "stable"

before_install:
  - docker build .
  - docker ps -a
  - docker run npm test

cache:
  directories:
    - "node_modules"

scrips:
  - npm test