language: node_js
services:
  - docker
node_js:
  - "stable"

before_install:
  - docker build -t service .
  - docker ps -a
  - docker run service /bin/sh -c "npm test"

cache:
  directories:
    - "node_modules"

script:
  - npm test